config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  patch 'users/:id' => 'users#update', as: 'update_user'
  resources :books, only: [:create, :index, :show, :edit, :destroy, :update]
  resources :users, only: [:index, :show, :edit]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :books, dependent: :destroy
  
  has_one_attached :profile_image
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
    
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = 'You have created book successfully.'
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user =  current_user
      render :index
    end
  end

  def show
    @book = Book.new
    @idbook = Book.find(params[:id])
    @user = @idbook.user
  end

  def edit
    @idbook = Book.find(params[:id])
    if current_user.id != @idbook.user_id
      redirect_to books_path
    end
  end
  
  def update
    @idbook = Book.find(params[:id])
    if @idbook.update(book_params)
      flash[:notice] = 'You have updated book successfully.'
      redirect_to book_path(@idbook.id)
    else
      render :edit
    end
  end
  
  def destroy
    @idbook = Book.find(params[:id])
    @idbook.destroy
    redirect_to books_path
  end
  
  private
  def book_params
    params.require(:book).permit(:title,:body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
    @user = User.find(current_user.id)
    @book = Book.new
  end
  
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    if current_user.id != params[:id].to_i
      redirect_to user_path(current_user.id)
    end
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'You have updated user successfully.'
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_user_info.html.erb
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag user.get_profile_image(100, 100) %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <%= link_to edit_user_path(@user.id), :class => "btn btn-outline-secondary btn-block mt-4" do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
      </div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: book do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, :class => "form-control book_title" %>
        </div>
        <div class="form-group">
          <label for="book_title">Opinion</label>
          <%= f.text_area :body, :class => "form-control book_body"  %>
        </div>
        <div class="form-group">
          <%= f.submit 'Create Book', :class => "btn btn-success" %>
        </div>
      <% end %>
    </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      
      <% if @idbook.errors.any? %> 
        <div id="error-explanation">
          <h3><%= @idbook.errors.count %> errors prohibited this obj from being saved:</h3>
          <ul>
            <% @idbook.errors.full_messages.each do |message| %>
              <li style="list-style: disc;"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      
      <%= form_with model: @idbook, url: update_book_path(@idbook.id), method: :patch do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, :class => "form-control book_title"  %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, :class => "form-control book_body"  %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book', :class => "btn btn-success"  %>
        </div>
      <% end %>
      <%= link_to 'Show', book_path(@idbook.id) %>
      |
      <%= link_to 'Back', books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  
  <% if @book.errors.any? %> 
    <div id="error-explanation">
      <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li style="list-style: disc;"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row">
    <%= render 'user_info', book: @book, user: @user %>
    
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td><%= link_to image_tag(book.user.get_profile_image(80, 80)), user_path(book.user.id) %></td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'user_info', book: @book, user: @user %>
    
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <td>
            <%= link_to user_path(@idbook.user_id) do %>
              <%= image_tag(@idbook.user.get_profile_image(100, 100)) %></br>
              <%= @idbook.user.name %>
            <% end %>
          </td>
          <td><%= link_to @idbook.title, book_path(@idbook.id) %></td>
          <td><%= @idbook.body %></td>
          <% if @idbook.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@idbook.id), :class => "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', destroy_book_path(@idbook.id),
              method: :delete, 'data-confirm' => "本当に消しますか？", :class => "btn btn-sm btn-danger" %></td>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!
    </h1>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in', new_user_session_path, :class => "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign up', new_user_registration_path, :class => "btn btn-success btn-sm btn-block sign_up" %> 
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=devise-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" 
          aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to user_path(current_user.id), :class => "nav-link text-light" do %>
                    <i class="fas fa-home"></i>
                    Home
                  <% end %>
                </li>
                <li>
                  <%= link_to users_path, :class => "nav-link text-light" do %>
                    <i class="fas fa-users"></i>
                    Users
                  <% end %>
                </li>
                <li>
                  <%= link_to books_path, :class => "nav-link text-light" do %>
                    <i class="fas fa-book-open"></i>
                    Books
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, :class => "nav-link text-light", method: :delete do %>
                    <i class="fas fa-sign-out-alt"></i>
                    Log out
                  <% end %>
                </li> 
              <% else %>
                <li>
                  <%= link_to root_path, :class => "nav-link text-light" do %>
                    <i class="fas fa-home"></i>
                    Home
                  <% end %>
                </li>
                <li>
                  <%= link_to about_path, :class => "nav-link text-light" do %>
                    <i class="fas fa-link"></i>
                    About
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path, :class => "nav-link text-light" do %>
                    <i class="fas fa-user-plus"></i>
                    Sign up
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path, :class => "nav-link text-light" do %>
                    <i class="fas fa-sign-in-alt"></i>
                    Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
     
    </header>
    
    <main>
    <% flash.each do |message_type, message| %>
      <%= content_tag :div, message, class: message_type %>
    <% end %>
    <p id="notice"></p>
    <%= yield %>
    </main>
    
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      
      <% if @user.errors.any? %> 
        <div id="error-explanation">
          <h3><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li style="list-style: disc;"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      
      <%= form_with model: @user, url: update_user_path(@user.id), method: :patch do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name, :class => "form-control name"  %>
        </div>
        <div class="form-group">
          <label for="user_image">Image</label>
          <%= f.file_field :profile_image, accept: "image/*", :class => "form-control-file user_image"  %>
        </div>
        <div class="form-group">
          <label for="user_introduction">Introduction</label>
          <%= f.text_area :introduction, :class => "form-control introduction"  %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update User', :class => "btn btn-secondary"  %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  
  <div class="row">
    <%= render 'books/user_info', book: @book, user: @user %>
    
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= image_tag(user.get_profile_image(100, 100)) %></td>
              <td><%= user.name %></td>
              <td><%= link_to 'Show', user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/user_info', book: @book, user: @user %>
    
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to image_tag(book.user.get_profile_image(80, 80)), user_path(book.user.id) %></td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>